name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install tox

      - name: Run tests
        run:
          tox -e py
